### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by riley-x** [riley-x/SankeyFlow#1]
- [x] Change [artist](https://github.com/riley-x/SankeyFlow/blob/main/sankeyflow/sankeyflow.py#L56) argument to artist_type
- [x] Check when len(flows) < 2 [here](https://github.com/riley-x/SankeyFlow/blob/main/sankeyflow/sankeyflow.py#L74)
- [x] Fix align_y for array-like [here](https://github.com/riley-x/SankeyFlow/blob/main/sankeyflow/sankeyflow.py#L476) and in tree_layout
